/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prosphar.gui.gui_form;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import com.jtattoo.plaf.smart.*;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    Thread thread;

    public class Progression implements Runnable {

        public void run() {
            jProgressBar1.setVisible(true);
            for (int j = 1; j < 100; j++) {
                jProgressBar1.setStringPainted(true);
                jProgressBar1.setValue(j);
                jProgressBar1.setString(j + "%");
                if (j == 99) {
                    dispose();
                    //new AdminPanel;
                    //AdminPanel homeAdminPanel = new AdminPanel();
                    //homeAdminPanel.show();
                    //new mdi().setVisible(true);
                    AdminPanel homeAdminPanel = new AdminPanel();
                    homeAdminPanel.show();
                }
                try {
                    Thread.sleep(100);
                } catch (Exception e) {
                }
            }
        }
    }

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        textField();
        textPass();
    }

    private void textField() {
        userText.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        // jTextField1.setBackground(new Color(0, 0, 0, 0));
        // jTextField1.setForeground(Color.decode("#7A8C8D"));
        userText.setSelectionColor(new Color(75, 175, 152));
        // JTextField busqueda = new JTextField(20);

        if (userText.getText().length() == 0) {
            userText.setText("Nom utilisateur");
            userText.setForeground(Color.decode("#7A8C8D"));
        }
    }

    private void textPass() {
        userPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        // jTextField1.setBackground(new Color(0, 0, 0, 0));
        // jTextField1.setForeground(Color.decode("#7A8C8D"));
        // jTextField1.setSelectionColor(new Color(75, 175, 152));
        // JTextField busqueda = new JTextField(20);

        if (userPass.getText().length() == 0) {
            userPass.setText("Mot de passe");
            userPass.setForeground(Color.decode("#7A8C8D"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userPass = new javax.swing.JPasswordField();
        userText = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 400));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 164, 121));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pngegg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(35, 166, 97));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Prosperite pharma");

        userPass.setBackground(new java.awt.Color(135, 233, 144));
        userPass.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        userPass.setText("Mot de passe");
        userPass.setFocusTraversalPolicyProvider(true);
        userPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userPassFocusLost(evt);
            }
        });

        userText.setBackground(new java.awt.Color(135, 233, 144));
        userText.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        userText.setText("Nom utilisateur");
        userText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userTextFocusLost(evt);
            }
        });

        buttonLogin.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(18, 18, 18));
        buttonLogin.setText("Connexion");
        buttonLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogin.setBackground(new Color(7, 164, 121));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        buttonLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonLoginKeyPressed(evt);
            }
        });

        jProgressBar1.setBackground(new java.awt.Color(35, 166, 97));
        jProgressBar1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userPass, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(userPass, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(820, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTextFocusGained
        // TODO add your handling code here:
        userText.setText("");
        userText.setForeground(new Color(50, 50, 50));
    }//GEN-LAST:event_userTextFocusGained

    private void userTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTextFocusLost
        // TODO add your handling code here:
        if (userText.getText().length() == 0) {
            userText.setText("Nom utilisateur");
            userText.setForeground(new Color(150, 150, 150));
        }
    }//GEN-LAST:event_userTextFocusLost

    private void userPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPassFocusGained
        // TODO add your handling code here:
        userPass.setText("");
        userPass.setForeground(new Color(50, 50, 50));
    }//GEN-LAST:event_userPassFocusGained

    private void userPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPassFocusLost
        // TODO add your handling code here:
        if (userPass.getPassword().length == 0) {
            userPass.setText("Mot de passe");
            userPass.setForeground(new Color(150, 150, 150));
        }
    }//GEN-LAST:event_userPassFocusLost

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        thread = new Thread(new Progression());
        String username = userText.getText();
        String password = userPass.getText();
        /*if (userName.equals("admin") && passWord.equals("abc")) {
            System.out.print("A la bien");
            AdminPanel homeAdminPanel = new AdminPanel();
            homeAdminPanel.show();
            dispose();
        }*/
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://127.0.0.1:8889/prosphar";
            String user = "root";
            String passwd = "root";
            Connection conn = DriverManager.getConnection(url, user, passwd);
            System.out.println("Connexion effective !");
            Statement stm = conn.createStatement();
            String query = "SELECT * FROM users WHERE pseudo='" + username + "' AND password='" + password + "'";
            ResultSet req = stm.executeQuery(query);
            if (req.next()) {
                int role = req.getInt("role_id");
                if (role == 1) {
                    thread.start();
//                    JOptionPane.showMessageDialog(null, "VOUS ETES CONNECTE EN TANT QUE ADMINISTRATEUR");
//                    dispose();
//                    AdminPanel homeAdminPanel = new AdminPanel();
//                    homeAdminPanel.show();
                } else {
                    thread.start();
                    JOptionPane.showMessageDialog(null, "VOUS ETES CONNECTE EN TANT QU'AGENT");
                    dispose();
                    AgentPanel homeAgent = new AgentPanel();
                    homeAgent.show();
                }

                //JOptionPane.showMessageDialog(homeAdminPanel, "You have successfully logged in");
            } else if (username.equalsIgnoreCase("root") && password.equalsIgnoreCase("root")) {
                JOptionPane.showMessageDialog(null, "VOUS ETES CONNECTE EN TANT QUE ADM DE SECOURS");
                thread.start();
                dispose();
                AdminPanel homeAdminPanel = new AdminPanel();
                homeAdminPanel.show();
            } else {
                System.out.println("Nom ou mot de passe incorrect");
                JOptionPane.showMessageDialog(null, "NOM OU MOT DE PASSE INCORRECT");
            }
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonLoginKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String username = userText.getText();
            String password = userPass.getText();
            /*if (userName.equals("admin") && passWord.equals("abc")) {
            System.out.print("A la bien");
            AdminPanel homeAdminPanel = new AdminPanel();
            homeAdminPanel.show();
            dispose();
        }*/
            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://127.0.0.1:8889/prosphar";
                String user = "root";
                String passwd = "root";
                Connection conn = DriverManager.getConnection(url, user, passwd);
                System.out.println("Connexion effective !");
                Statement stm = conn.createStatement();
                String query = "SELECT * FROM users WHERE pseudo='" + username + "' AND password='" + password + "'";
                ResultSet req = stm.executeQuery(query);
                if (req.next()) {
                    int role = req.getInt("role_id");
                    if (role == 1) {
                        JOptionPane.showMessageDialog(null, "VOUS ETES CONNECTE EN TANT QUE ADMINISTRATEUR");
                        dispose();
                        AdminPanel homeAdminPanel = new AdminPanel();
                        homeAdminPanel.show();
                    } else {
                        JOptionPane.showMessageDialog(null, "VOUS ETES CONNECTE EN TANT QU'AGENT");
                        dispose();
                        AgentPanel homeAgent = new AgentPanel();
                        homeAgent.show();
                    }

                    //JOptionPane.showMessageDialog(homeAdminPanel, "You have successfully logged in");
                } else if (username.equals("root") && password.equals("root")) {
                    JOptionPane.showMessageDialog(null, "VOUS ETES CONNECTE EN TANT QUE ADM DE SECOURS");
                    dispose();
                    AdminPanel homeAdminPanel = new AdminPanel();
                    homeAdminPanel.show();
                } else {
                    System.out.println("Nom ou mot de passe incorrect");
                    JOptionPane.showMessageDialog(null, "NOM OU MOT DE PASSE INCORRECT");
                }
            } catch (SQLException sqlException) {
                sqlException.printStackTrace();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("Nom ou mot de passe incorrect");
            JOptionPane.showMessageDialog(null, "NOM OU MOT DE PASSE INCORRECT");

        }
    }//GEN-LAST:event_buttonLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme("rgb(35,166,97)", "INSERT YOUR LICENSE KEY HERE", "my company");      //   1
//            com.jtattoo.plaf.aero.AeroLookAndFeel.setTheme("Blue", "INSERT YOUR LICENSE KEY HERE", "my company");      //   2
//            com.jtattoo.plaf.aluminium.AluminiumLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "my company");      //   3
//            com.jtattoo.plaf.bernstein.BernsteinLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "my company");      //   4
//            com.jtattoo.plaf.fast.FastLookAndFeel.setTheme("Blue", "INSERT YOUR LICENSE KEY HERE", "my company");      //   5
//            com.jtattoo.plaf.graphite.GraphiteLookAndFeel.setTheme("Red", "INSERT YOUR LICENSE KEY HERE", "my company");      //   6
//            com.jtattoo.plaf.hifi.HiFiLookAndFeel.setTheme("Blue", "INSERT YOUR LICENSE KEY HERE", "my company");      //   7
//            com.jtattoo.plaf.luna.LunaLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "my company");      //   8
//            com.jtattoo.plaf.mcwin.McWinLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "my company");      //   9
//            com.jtattoo.plaf.noire.NoireLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "my company");      //   10
//            com.jtattoo.plaf.smart.SmartLookAndFeel.setTheme("Blue", "INSERT YOUR LICENSE KEY HERE", "my company");      //   11
//            com.jtattoo.plaf.texture.TextureLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "my company");      //   12

            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");   //   1
//            UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");          //   2
//            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");//   3
//            UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");//   4 
//            UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");          //   5
//            UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");  //   6
//            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");          //   7
//            UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");          //   8
//            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");        //   9
//            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");        //   10
//            UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");        //   11
//            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");     //  12
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPasswordField userPass;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
