/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prosphar.gui.gui_form;

import java.awt.Color;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.Random;
import java.util.logging.Level;
import java.util.ArrayList;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import com.jtattoo.plaf.smart.*;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.util.Locale;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author user
 */
public final class Update extends javax.swing.JFrame {

    private String nomProduit;

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    Update(String nomProduit) {
        this.nomProduit = nomProduit;
        initComponents();
        afficherProduit();
    }

    public void afficherProduit() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://127.0.0.1:8889/prosphar";
            String user = "root";
            String passwd = "root";
            Connection conn = DriverManager.getConnection(url, user, passwd);
            System.out.println("Connexion effective !");
            Statement stm = conn.createStatement();
            String query = "SELECT * FROM produits WHERE nom='" + nomProduit + "'";
            ResultSet req = stm.executeQuery(query);
            if (req.next()) {
                Date datee = req.getDate("date_exp");
                String quant = req.getString("qte_produit");
                String prixAchat = req.getString("prix_achat");
                String prixVente = req.getString("prix_vente");
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy");
                String theDate = dateFormat.format(datee);

                System.out.print("DATE :" + theDate);

                prodUp.setText(nomProduit);
                //dateExpiUp.setCalendar(datee);
                qteProdUp.setText(quant);
                prixAchatUp.setText(prixAchat);
                prixVenteUp.setText(prixVente);

            }
            req.close();
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CategUp = new javax.swing.JComboBox<>();
        prodUp = new javax.swing.JTextField();
        qteProdUp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        prixAchatUp = new javax.swing.JTextField();
        prixVenteUp = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        dateExpiUp = new com.toedter.calendar.JDateChooser();
        btnDeleteUp = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)), "MODIFICATION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setText("Nom produit");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel10.setText("Quantite produit");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel12.setText("Categorie produit");

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel17.setText("Date d'expiration");

        CategUp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        CategUp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPRIME", "SIROP", "INJECTABLE", "SUPPO", "GOUTTE", "CREME", "POUDRE", "SAVON", "POMMADE", "SPRITE", "SOLUTION", "GEL", "MATERIEL", "SERUM", "AUTRES" }));
        CategUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        prodUp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        prodUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qteProdUp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        qteProdUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel18.setText("Prix d'achat");

        prixAchatUp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        prixAchatUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        prixVenteUp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        prixVenteUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setText("Prix de vente");

        dateExpiUp.setBackground(new java.awt.Color(255, 255, 255));
        dateExpiUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dateExpiUp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategUp, 0, 182, Short.MAX_VALUE)
                    .addComponent(prodUp)
                    .addComponent(qteProdUp)
                    .addComponent(prixAchatUp)
                    .addComponent(prixVenteUp)
                    .addComponent(dateExpiUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prodUp)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategUp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateExpiUp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qteProdUp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prixAchatUp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prixVenteUp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnDeleteUp.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnDeleteUp.setText("SUPPRIMER");
        btnDeleteUp.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        btnDeleteUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUpActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnUpdate.setText("MODIFIER");
        btnUpdate.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteUp, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteUp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://127.0.0.1:8889/prosphar";
            String user = "root";
            String passwd = "root";
            Connection conn = DriverManager.getConnection(url, user, passwd);
            System.out.println("Connexion effective !");
            String name = prodUp.getText();
            String categorie = CategUp.getSelectedItem().toString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String datee = dateFormat.format(dateExpiUp.getDate());
            int qte = Integer.parseInt(qteProdUp.getText());
            double prixAchat = Double.parseDouble(prixAchatUp.getText());
            double prixVente = Double.parseDouble(prixVenteUp.getText());
            int categorieId;

            if (categorie.equalsIgnoreCase("comprime")) {
                categorieId = 1;
            } else if (categorie.equalsIgnoreCase("sirop")) {
                categorieId = 2;
            } else if (categorie.equalsIgnoreCase("injectable")) {
                categorieId = 3;
            } else if (categorie.equalsIgnoreCase("suppo")) {
                categorieId = 4;
            } else if (categorie.equalsIgnoreCase("goutte")) {
                categorieId = 5;
            } else if (categorie.equalsIgnoreCase("creme")) {
                categorieId = 6;
            } else if (categorie.equalsIgnoreCase("poudre")) {
                categorieId = 7;
            } else if (categorie.equalsIgnoreCase("savon")) {
                categorieId = 8;
            } else if (categorie.equalsIgnoreCase("pommade")) {
                categorieId = 9;
            } else if (categorie.equalsIgnoreCase("sprite")) {
                categorieId = 10;
            } else if (categorie.equalsIgnoreCase("solution")) {
                categorieId = 11;
            } else if (categorie.equalsIgnoreCase("gel")) {
                categorieId = 12;
            } else if (categorie.equalsIgnoreCase("materiel")) {
                categorieId = 13;
            } else if (categorie.equalsIgnoreCase("serum")) {
                categorieId = 15;
            } else if (categorie.equalsIgnoreCase("autres")) {
                categorieId = 15;
            } else {
                categorieId = 0; // Valeur par défaut si la catégorie ne correspond à aucun des cas
            }
            Statement stm = conn.createStatement();
            String query = "SELECT * FROM produits WHERE nom='" + nomProduit + "'";
            ResultSet req = stm.executeQuery(query);

            if (req.next()) {
                String quant = req.getString("qte_produit");
                int quanti = Integer.parseInt(quant);
                String sql = String.format("UPDATE produits SET nom = ?, categorie_id= ?, date_exp= ?, qte_produit= %d + ?, prix_achat= ?, prix_vente= ? WHERE nom = ?", quanti);
                try (PreparedStatement preparedStatement = conn.prepareStatement(sql)) {
                    preparedStatement.setString(1, name);
                    preparedStatement.setInt(2, categorieId);
                    preparedStatement.setString(3, datee);
                    preparedStatement.setInt(4, qte);
                    preparedStatement.setDouble(5, prixAchat);
                    preparedStatement.setDouble(6, prixVente);
                    preparedStatement.setString(7, name);
                    int rowsUpdated = preparedStatement.executeUpdate();
                    // Vérifier si la mise à jour a réussi
                    if (rowsUpdated > 0) {
                        System.out.println("Mise à jour effectuée avec succès.");
                        JOptionPane.showMessageDialog(this, "MISE A JOUR DU " + nomProduit.toUpperCase() + " EFFECTUEE AVEC SUCCES.");
                        prodUp.setText("");
                        //dateExpiUp.setCalendar(datee);
                        qteProdUp.setText("");
                        prixAchatUp.setText("");
                        prixVenteUp.setText("");
                    } else {
                        System.out.println("Échec de la mise à jour.");
                    }
                    // Fermer les ressources
                }
                conn.close();

            }
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUpActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://127.0.0.1:8889/prosphar";
            String user = "root";
            String passwd = "root";
            Connection conn = DriverManager.getConnection(url, user, passwd);
            System.out.println("Connexion effective !");
            String sql = "DELETE FROM produits WHERE nom=?";
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, nomProduit); // Remplacez 'id' par la valeur de l'identifiant de l'élément à supprimer
            int rowsDeleted = statement.executeUpdate();
            if (rowsDeleted > 0) {
                System.out.println("L'élément a été supprimé avec succès de la base de données.");
                int choice = JOptionPane.showConfirmDialog(null, " VEUX-TU SUPPRIMER " + nomProduit.toUpperCase() + " DE LA BASE DE DONNEE ?", "Confirmation", JOptionPane.OK_CANCEL_OPTION);
                if (choice == JOptionPane.OK_OPTION) {
                    JOptionPane.showMessageDialog(this, nomProduit.toUpperCase() + " SUPPRIME ");
                    prodUp.setText("");
                    //dateExpiUp.setCalendar(datee);
                    qteProdUp.setText("");
                    prixAchatUp.setText("");
                    prixVenteUp.setText("");
                } else if (choice == JOptionPane.CANCEL_OPTION) {
                    System.out.println("Vous avez cliqué sur Annuler !");
                }
            } else {
                System.out.println("Impossible de supprimer l'élément de la base de données.");
            }

        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CategUp;
    private javax.swing.JButton btnDeleteUp;
    private javax.swing.JButton btnUpdate;
    private com.toedter.calendar.JDateChooser dateExpiUp;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField prixAchatUp;
    private javax.swing.JTextField prixVenteUp;
    private javax.swing.JTextField prodUp;
    private javax.swing.JTextField qteProdUp;
    // End of variables declaration//GEN-END:variables
}
